### ISSUE TITLE
Always 30px

### ISSUE THREAD

**Issue by FluffyDiscord** [ux-ui-pro/text-fitting#1]
I can't get this package to work. It creates the shadow elements, and applies styles, but it always applies 30px and text still overflows. Anything I am doing wrong?
![image](https://github.com/ux-ui-pro/text-fitting/assets/10332247/f846d088-1bbb-4c15-802a-1c42fc0de51e)
![image](https://github.com/ux-ui-pro/text-fitting/assets/10332247/3b88f78c-75f9-4e46-be5b-7a3f0b10a0e7)

**Comment by ux-ui-pro** [comment]
Unfortunately, without a code sample it is hard to guess what your problem might be. Probably the width of the parent container cannot be read.

In theory, you could use this package for what is shown in your image, like this: [https://codepen.io/ux-ui/pen/WNLGLaz](https://codepen.io/ux-ui/pen/WNLGLaz). But in general, this is not a good idea.

This package is more suited for slightly different tasks, such as creating large headers that take up the entire width of the template.

![Component2](https://github.com/ux-ui-pro/text-fitting/assets/51360899/116f75d0-89f0-4ddb-8a07-8fde3553787e)

**Comment by FluffyDiscord** [comment]
Wrapping the element in "div" instead of "h4" and applying styles to it directly seems to make it work

**Comment by ux-ui-pro** [comment]
Without seeing the sample code, it's hard to guess what exactly is going on.

For TextFitting to work correctly, you need to explicitly specify the width of the parent block in relative units.

When using length units or numeric values, the size of the parent block depends on the size of its container, not the content. ResizeObserver will not detect changes to the size of the parent block, so the update method will not be called.

I've added a couple more examples, and an example with the H4 tag: [https://codepen.io/ux-ui/pen/WNLGLaz](https://codepen.io/ux-ui/pen/WNLGLaz).
